#!/bin/bash

# Desenvolvedor: Rafael Silva Santos
# Descrição: Programa que realiza scan networks para coletar ativos, scan de portas essenciais.

# dependencias
DIR="/home/rafael/scan"
source $DIR/vars/variaveis && source $DIR/moduls/*

# Programa
clear && t1

for i in {1..254}; do timeout 0.17 /bin/bash -c "ping -c1 $NETWORK.$i" &> /dev/null; if [[ $? = 0 ]]; then IP=("${IP[@]}" "$NETWORK.$i"); fi; t2; done

clear && t3; for i in "${IP[@]}"; do t4; done && echo; t5 && read && clear && t6

for X in "${IP[@]}"; do t7
    for i in "${portas[@]}"; do timeout 0.01 /bin/bash -c "echo scan > /dev/tcp/$X/$i" 2> /dev/null; if [[ $? = 0 ]]; then t8; fi; done && echo
done

t5 && read && clear
