#!/bin/bash

# Descrição: script para verificar cabo conectado nas placas de rede

if [[ $UID != 0 ]]; then echo "programa deve ser executado com privilegio de administrador" ; exit 1 ; fi

function get_interface(){
    interfaces=$(ip --brief link show | awk -F' ' '{ print $1 }' )
}

function verify_link(){
    for i in ${interfaces[@]}; do echo "$i\t$(ethtool $i | grep -i 'link detected' )" ; done
}

get_interface && verify_link
