#!/bin/bash

# Descrição: script para verificar cabo conectado nas placas de rede

getinterface() {
        interfaces=$(ifconfig -a | grep -i 'mtu' | awk -F: '{ print $1 }')
}

getmac() {
        mac=$(echo $(ip --brief link show $i | awk '{ print $3 }' | egrep ^[0-9]                                                                                        {2}:))
        [[ -z $mac ]] && mac=$(echo -e 'xx:xx:xx:xx:xx:xx')
        printf "$mac\n"
}

getip() {
        ip=$(echo $(ip addr show $i 2> /dev/null | grep 'inet ' | awk  '{ print                                                                                         $2 }' | awk -F/ '{print $1}'))
        [[ -z $ip ]] && ip=$(echo "")
        printf "$ip\n" | sed 's/ /\n\t\t\t\t\t/g'
}

getsubmasc() {
        subnet=$(echo $(ifconfig $i | grep netmask | awk '{ print $4 }'))
        [[ -z $subnet ]] && subnet=$(echo -e "\t\t")
        printf "$subnet\n"
}

checkLink() {
        statuslink=$(ethtool $i 2> /dev/null | grep -i 'link detected')
        [[ -z $statuslink ]] && statuslink=$(echo -e "\t\t\t")
        printf "\t$statuslink\n"
}

listresult() {
        for i in ${interfaces[*]}; do
                printf "$i$(checkLink)\t$(getip)\t\t$(getsubmasc)\t\t$(getmac)\n                                                                                        "
        done
}

play() {
        printf "Inteface-name\tStatus-of-link\t\tIP-address\t\tSubmask\t\t\tMAC-                                                                                        address\t\n\n"
        getinterface && listresult
}

play && printf "\nPublic address: $(wget -qO- http://ipecho.net/plain)\n"
